MEPTS-1129 | New Report List of Patients With High Viral Load
jembi/openmrs-module-eptsreports pull request #1008
Opened 2023-07-17 06:50 UTC by Emmanuel0077

2023-07-17 08:53 UTC, helderjosue commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/data/converter/VlResultClassificationConverter.java
> +    int value = (int) valueInDoubleform;
This verification is not needed! The VL result is an integer value and its not recorded as doubles.

2023-07-18 07:08 UTC, helderjosue commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/datasets/ListOfPatientsWithHighViralLoadCohortDataset.java
> +        "evaluationDate=${evaluationDate}",
Use endDate instead of evaluationDate to calculate the age **FR8**
Make the same change on SemanaCorrenteDataset

2023-07-18 07:17 UTC, helderjosue commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/datasets/ListOfPatientsWithHighViralLoadCohortDataset.java
> +    pdd.addColumn("id", new PersonIdDataDefinition(), "");
Remove unused column

2023-07-18 07:25 UTC, helderjosue commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/reports/SetupListOfPatientsWithHighViralLoad.java
> +        new Parameter("evaluationDate", "Evaluation Date", Date.class),
Remove the unused parameter

2023-07-18 07:29 UTC, helderjosue commented on api/src/main/resources/ListPatientWithHighViralLoad_v1.0.xls
All dates across the template should use ForwardSlash instead of hyphen (-)
Format all Date columns to use the same format from column **Data De  Inicio tarv**

2023-07-18 07:43 UTC, helderjosue commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/reports/SetupListOfPatientsWithHighViralLoad.java
> +    return "List of Patients with High Viral Load Cohort Report";
Update the name of the report to **List for Follow-up of Patients with Unsuppressed Viral Load** FR1

2023-07-18 07:45 UTC, helderjosue commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/reports/SetupListOfPatientsWithHighViralLoad.java
> +    return "Lista de Pacientes com Carga Viral Alta";
Update the description of the report for **Lista de Seguimento De Pacientes Com Carga Viral Não Suprimida** FR1

2023-08-03 13:53 UTC, helderjosue approved these changes
Looks good to me! 
Ready for next review

2023-08-22 07:26 UTC, psmatsinhe requested changes
@helderjosue please have a look

2023-08-22 07:26 UTC, psmatsinhe commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/queries/HighViralLoadQueries.java
> +  public static String getSessionZeroQuery() {
This one could be private

2023-08-22 07:26 UTC, psmatsinhe commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/queries/HighViralLoadQueries.java
> +        + HighViralLoadQueries.getSessionZeroQuery()
no need to call the class name, just the method

2023-08-22 07:26 UTC, psmatsinhe commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/queries/HighViralLoadQueries.java
> +        + HighViralLoadQueries.getSessionOneQuery()
same

2023-08-22 07:26 UTC, psmatsinhe commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/queries/HighViralLoadQueries.java
> +            + "WHERE  p.voided = 0 "
It is the same until here

2023-09-05 05:00 UTC, psmatsinhe approved these changes
Looks good to me

2023-09-05 05:00 UTC, merged