MEPTS 1310 | MI Template New Version - September Release
jembi/openmrs-module-eptsreports pull request #1027
Opened 2023-09-01 14:42 UTC by TinoMuianga

2023-09-04 08:32 UTC, helderjosue commented on api/src/main/resources/SESP_Template_MI_2023.xls
You just added a new template and did remove the previous! Please remove it from the projects resources.

2023-09-04 08:51 UTC, helderjosue commented on api/src/main/resources/SESP_Template_MI_2023.xls
- Please add the report generation date on the template (sheet2)
- The column DT10 (sheet 2 ) does not have its mappings (looks like a formula)

2023-09-04 09:06 UTC, helderjosue requested changes
Please check and update the code based on the comments

2023-09-04 10:16 UTC, helderjosue approved these changes
Looks good, ready for next review!

2023-09-05 05:01 UTC, psmatsinhe approved these changes
Looks good to me

2023-09-05 05:01 UTC, merged