MEPTS-1349 | TXCURR CHANGES DECEMBER
jembi/openmrs-module-eptsreports pull request #1067
Opened 2023-11-15 14:06 UTC by helderjosue

2023-11-16 10:35 UTC, psmatsinhe requested changes
Have a look

2023-11-16 10:35 UTC, psmatsinhe commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TxCurrCohortQueries.java
> -          "(1 OR 2 OR 3 OR 4 OR 5) AND NOT ((6 OR 7 OR 8 OR 9 OR 11 OR ((10 OR 15 OR transferredOutProgram) AND mostRecentSchedule)) AND NOT 12) AND NOT (13 OR 14)";
You not using the 5, you should remove from the map

2023-11-16 12:38 UTC, helderjosue commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TxCurrCohortQueries.java
> -          "(1 OR 2 OR 3 OR 4 OR 5) AND NOT ((6 OR 7 OR 8 OR 9 OR 11 OR ((10 OR 15 OR transferredOutProgram) AND mostRecentSchedule)) AND NOT 12) AND NOT (13 OR 14)";
done

2023-11-20 07:50 UTC, psmatsinhe approved these changes
Looks good to me

2023-11-20 07:50 UTC, merged