MEPTS 1348 | TX RTT Changes for December 2023 Release
jembi/openmrs-module-eptsreports pull request #1068
Opened 2023-11-16 12:16 UTC by TinoMuianga

…of not eligible for cd4) on TXRTT and Refactor on java doc of TXNEW for CD4Results

2023-11-23 11:32 UTC, eliazmuchave requested changes
Left comments. Take a look

2023-11-23 11:32 UTC, eliazmuchave commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TxRttCohortQueries.java
> +    cd.addParameter(new Parameter("startDate", "Start Date", Date.class));
Start date is never used

2023-11-23 11:32 UTC, eliazmuchave commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TxRttCohortQueries.java
> +   * Patients whose first ever drug pick-up date between the following sources falls during the
FR 4 The pickup falls by the end of previous reporting period

2023-11-23 11:32 UTC, eliazmuchave commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TxRttCohortQueries.java
> +    return cd;
FR4 - The pickup falls by the end of previous reporting period

2023-11-23 11:32 UTC, eliazmuchave commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TxRttCohortQueries.java
> +            + commonQueries.getARTStartDate(true)
You are mapping report end date to Art start cohort, but according to the requirement the date falls by previous period

2023-11-23 11:32 UTC, eliazmuchave commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TxRttCohortQueries.java
> +            + commonQueries.getARTStartDate(true)
You are mapping report end date to Art start cohort, but according to the requirement the date falls by previous period

2023-11-23 11:32 UTC, eliazmuchave commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TxRttCohortQueries.java
> +            + commonQueries.getFirstDrugPickup()
You are mapping report end date to first drug pickup cohort, but according to the requirement the date falls by previous period

2023-11-23 11:32 UTC, eliazmuchave commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TxRttCohortQueries.java
> +  }
Does not meet the requirements

2023-11-24 07:25 UTC, TinoMuianga commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TxRttCohortQueries.java
> +  }
This i d done

2023-11-24 07:26 UTC, TinoMuianga commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TxRttCohortQueries.java
> +            + commonQueries.getFirstDrugPickup()
Done, mapped for previous reporting date

2023-11-24 07:26 UTC, TinoMuianga commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TxRttCohortQueries.java
> +            + commonQueries.getARTStartDate(true)
Done, mapped for previous reporting date

2023-11-24 09:54 UTC, eliazmuchave requested changes

2023-11-24 09:54 UTC, eliazmuchave commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TxRttCohortQueries.java
> +    cd.addParameter(new Parameter("startDate", "Start Date", Date.class));
Never used

2023-11-24 09:54 UTC, eliazmuchave commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TxRttCohortQueries.java
> +            + "AND  Timestampdiff(DAY, restarted.pick_up_date, "
Check param order

2023-11-24 12:54 UTC, eliazmuchave approved these changes
Looks good to me

2023-11-24 12:55 UTC, merged