MEPTS-1422 | LISTA DE DAH DIFF FGH
jembi/openmrs-module-eptsreports pull request #1136
Opened 2024-02-26 08:59 UTC by helderjosue

2024-02-28 08:15 UTC, psmatsinhe requested changes
Please check

2024-02-28 08:15 UTC, psmatsinhe commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/queries/advancedhivillness/ListOfPatientsOnAdvancedHivIllnessQueries.java
> +        + "  AND o.value_numeric < 200  "
same as the other ticket, please use parameters and if possible use the same method

2024-02-28 12:19 UTC, helderjosue commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/queries/advancedhivillness/ListOfPatientsOnAdvancedHivIllnessQueries.java
> +        + "  AND o.value_numeric < 200  "
Implemented

2024-03-07 07:18 UTC, psmatsinhe requested changes
@helderjosue please see

2024-03-07 07:18 UTC, psmatsinhe commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/reports/SetupListOfPatientsInAdvancedHivIllness.java
> +@Component
Why?

2024-03-07 07:57 UTC, helderjosue commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/reports/SetupListOfPatientsInAdvancedHivIllness.java
> +@Component
corrected

2024-03-12 07:24 UTC, psmatsinhe approved these changes
Looks good to me

2024-03-12 07:24 UTC, merged