MEPTS-570-sql: TX CURR on sqlcohortdefinitions
jembi/openmrs-module-eptsreports pull request #223
Opened 2020-08-27 16:53 UTC by amosh101

2020-09-08 13:36 UTC, cfaife requested changes

2020-09-08 13:39 UTC, amosh101 commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/reports/SetupMERQuarterly24.java
> +    /*rd.addDataSetDefinition("P", Mapped.mapStraightThrough(txPvlsDataset.constructTxPvlsDatset()));
Done

2020-09-08 13:39 UTC, amosh101 commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/reports/SetupMERQuarterly24.java
> +    rd.addDataSetDefinition("R", Mapped.mapStraightThrough(txRttDataset.constructTxRttDataset()));*/
Done

2020-09-08 14:02 UTC, amosh101 commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/reports/SetupMERQuarterly24.java
> +    /*rd.addDataSetDefinition("N", Mapped.mapStraightThrough(txNewDataset.constructTxNewDataset()));*/
Done

2020-09-09 06:28 UTC, cfaife approved these changes

2020-09-09 06:28 UTC, merged