Mepts 848 cat11 change
jembi/openmrs-module-eptsreports pull request #550
Opened 2021-06-07 22:57 UTC by psmatsinhe

2021-06-08 10:56 UTC, ItsMurumba approved these changes

2021-06-08 11:17 UTC, ItsMurumba commented
Need to fix some conflicts with develop @psmatsinhe

2021-06-08 11:20 UTC, ItsMurumba requested changes
Fix merge conflict @psmatsinhe

2021-06-08 11:44 UTC, ItsMurumba approved these changes

2021-06-09 08:43 UTC, cfaife approved these changes

2021-06-09 08:43 UTC, cfaife commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/IntensiveMonitoringCohortQueries.java
>        TbMetadata tbMetadata,
from here to above(lines 25 - 28) we need to remove the constructor parameters(hivMetadata,commonMetadata,commonCohortQueries,tbMetadata), They are not in use

2021-06-09 08:43 UTC, merged