Mepts 884 improve code legibility
jembi/openmrs-module-eptsreports pull request #595
Opened 2021-07-19 06:01 UTC by ItsMurumba

Improved Code Readability by replacing strings with ENUM and Boolean where applicable. The changes affect both MQ and MI reports.

2021-07-20 10:20 UTC, iteliolucas requested changes
Please fix compilation errors

2021-07-21 05:23 UTC, ItsMurumba commented
> Please fix compilation errors

The compilation runs successfully on my machine and also have tested the module in Bugatti @iteliolucas

2021-07-27 03:10 UTC, ningosi approved these changes

2021-07-27 03:12 UTC, ningosi approved these changes

2021-07-27 03:13 UTC, ningosi commented
@iteliolucas this pass all the checks, please approve since there were pending changes you requested on it

2021-07-27 07:46 UTC, iteliolucas approved these changes

2021-07-27 08:46 UTC, merged