MEPTS-900 | List of Patients Defaulters or IIT - Template v1.3
jembi/openmrs-module-eptsreports pull request #603
Opened 2021-08-12 12:31 UTC by rupansana12

2021-08-18 10:01 UTC, ItsMurumba requested changes
Hey, @rupansana12 I left some comments on the PR. Kindly address them. Thanks

2021-08-18 10:01 UTC, ItsMurumba commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/reports/SetupListOfPatientsDefaultersOrIITReport.java
> +              "Template_List_Patients_Defaulters_IIT_TARV_v1.3.xls",
Can we change the name of the template to **List_Patients_Defaulters_IIT_TARV_v1.3.xls**?

2021-08-18 10:01 UTC, ItsMurumba commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/reports/SetupListOfPatientsDefaultersOrIITReport.java
>                "Template List Patients Defaulters IIT TARV Report",
Same as the previous comment. We remove the word **Template** from the name

2021-08-19 06:39 UTC, ItsMurumba reviewed
Looks okay. Ready to be merged.

2021-08-19 06:40 UTC, ItsMurumba approved these changes

2021-08-20 07:21 UTC, cfaife approved these changes

2021-08-20 07:21 UTC, merged