MEPTS-901 | list of patients defaulters or iit
jembi/openmrs-module-eptsreports pull request #606
Opened 2021-08-26 06:33 UTC by helderjosue

2021-08-30 07:46 UTC, ItsMurumba requested changes
1. Age: This is based on endDate and what we are currently using is based on the current date. Check List of Children Dataset.
2. Add Parameters to the **constructDataSet** DatasetDefinition.
cc @helderjosue @rupansana12

2021-08-30 08:05 UTC, ItsMurumba requested changes
In the cohort queries, supply the correct datadefibition set name for the following:

1. getLocation()
2.  getContact()
3. getNeighborhood()
4. getReferencePoint()
5. getPatientsMarkedNo()

2021-08-30 08:05 UTC, ItsMurumba commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/ListOfPatientsDefaultersOrIITCohortQueries.java
>      sqlPatientDataDefinition.setName("All patients marked as: Sim");
Update the setName to Location

2021-08-30 09:12 UTC, helderjosue commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/ListOfPatientsDefaultersOrIITCohortQueries.java
>      sqlPatientDataDefinition.setName("All patients marked as: Sim");
All implemented

2021-09-02 10:21 UTC, cfaife requested changes

2021-09-02 10:21 UTC, cfaife commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/data/definition/CurrentDateDataDefinition.java
> +public class CurrentDateDataDefinition {}
is this class in use?

2021-09-02 10:27 UTC, rupansana12 commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/data/definition/CurrentDateDataDefinition.java
> +public class CurrentDateDataDefinition {}
we are not using, I'm going to remove.

2021-09-06 06:37 UTC, cfaife approved these changes

2021-09-06 07:13 UTC, ItsMurumba approved these changes

2021-09-06 07:30 UTC, merged