Mepts 936 | Change VL Relatoio Faltosos ARV
jembi/openmrs-module-eptsreports pull request #652
Opened 2021-11-16 11:53 UTC by eliazmuchave

2021-11-17 08:20 UTC, iteliolucas requested changes
The subquery item _'vl_registered.encounter_type'_ is never used. I suggest you remove it.

2021-11-17 08:26 UTC, iteliolucas requested changes
It is generally considered bad practice to leave spaces between the table name, the dot and the column you are refering to ex: _encounter_51 .encounter_id_.  I would recommend you remove those spaces.

2021-11-17 09:33 UTC, eliazmuchave commented
All changes made on commit f2abaeb

2021-11-17 09:35 UTC, iteliolucas approved these changes

2021-11-18 11:17 UTC, ningosi approved these changes

2021-11-18 11:17 UTC, merged