MEPTS-947:added the template
jembi/openmrs-module-eptsreports pull request #665
Opened 2021-11-29 19:41 UTC by cfaife

2021-11-30 09:15 UTC, eliazmuchave requested changes
1. The location and report period mappings are swapped on the template
2. The IG and IF columns are not mapped. Also C

2021-12-01 07:35 UTC, eliazmuchave approved these changes

2021-12-01 07:38 UTC, eliazmuchave commented
Looks good. Can be merged

2021-12-01 08:29 UTC, psmatsinhe approved these changes
Looks good to me

2021-12-01 08:29 UTC, merged