MEPTS-943 | MOH New Report Viral Load DQA
jembi/openmrs-module-eptsreports pull request #669
Opened 2021-12-02 07:39 UTC by iteliolucas

2021-12-03 08:10 UTC, cfaife requested changes

2021-12-03 08:10 UTC, cfaife commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/data/converter/ForwardSlashDateConverter.java
> +    return formatDate((Date) obj);
to avoid ClassCastExceptoin, you should add  a check  to verify if  the  obj is instance of Date.class

2021-12-03 08:10 UTC, cfaife commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/datasets/DQACargaViralDataset.java
> +    Map<String, Integer> valuesMap = new HashMap<>();
i dont see the need of this map,  there is no data   in it,

2021-12-03 08:51 UTC, iteliolucas commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/data/converter/ForwardSlashDateConverter.java
> +    return formatDate((Date) obj);
Done avoiding ClassCastExceptoin,

2021-12-06 07:16 UTC, cfaife commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/data/converter/ForwardSlashDateConverter.java
> +    return formatDate((Date) obj);
good

2021-12-06 07:19 UTC, cfaife approved these changes

2021-12-06 07:19 UTC, merged