MEPTS | 1029 Relatorio Faltosos Template Update
jembi/openmrs-module-eptsreports pull request #738
Opened 2022-04-04 08:30 UTC by eliazmuchave

2022-04-05 09:55 UTC, ItsMurumba requested changes
@eliazmuchave I see some columns that have not been mapped. Is this a deliberate omission or needs to be fixed?

2022-04-05 10:10 UTC, eliazmuchave commented
@ItsMurumba These columns were not specified yet, so I didn't map it. It will be mapped on another ticket (Change Request)

2022-04-05 10:18 UTC, ItsMurumba approved these changes

2022-04-06 15:09 UTC, ningosi approved these changes

2022-04-06 15:10 UTC, merged