MEPTS-1012 | TPT INITIATION CHANGES
jembi/openmrs-module-eptsreports pull request #749
Opened 2022-05-05 07:57 UTC by TinoMuianga

2022-05-09 07:46 UTC, eliazmuchave requested changes

2022-05-09 07:46 UTC, eliazmuchave commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TPTInitiationCohortQueries.java
> +            + "  OR o2.value_coded IS NULL "
Check this condition. It doesn't seem to implement the specification correctly

2022-05-09 07:46 UTC, eliazmuchave commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TPTInitiationCohortQueries.java
> +            + "       "
Remove whitespaces

2022-05-09 07:46 UTC, eliazmuchave commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TPTInitiationCohortQueries.java
> +            + "      INNER JOIN (  SELECT p.patient_id, e.encounter_datetime AS start_date "
The system will consider the oldest date amongst all sources as the 3HP Start Date - This note wasn't implemented

2022-05-09 07:46 UTC, eliazmuchave commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TPTInitiationCohortQueries.java
> +            + "        OR o2.concept_id = ${23985} "
The patient must have had both 'Profilaxia TPT' and 'Estado Profilaxia' to be eligible

2022-05-09 07:46 UTC, eliazmuchave commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TPTInitiationCohortQueries.java
> +        "SELECT p.patient_id "
This query exists in the code, you can reuse it

2022-05-09 07:46 UTC, eliazmuchave commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TPTInitiationCohortQueries.java
> +            + "                           OR o2.value_coded IS NOT NULL "
This preposition isn't according to specification

2022-05-09 07:46 UTC, eliazmuchave commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TPTInitiationCohortQueries.java
> +            + "                                       AND e.location_id = :location "
Specify the encounter type in the exclusions queries

2022-05-09 07:46 UTC, eliazmuchave commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TPTInitiationCohortQueries.java
> +        "SELECT p.patient_id "
The system will consider the oldest date amongst all sources as the IPT Start Date

2022-05-09 07:46 UTC, eliazmuchave commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TPTInitiationDataDefinitionQueries.java
> +            + "           AND e.encounter_datetime < Curdate() "
remove this condition

2022-05-16 13:35 UTC, helderjosue reviewed
please check the comments

2022-05-16 13:35 UTC, helderjosue commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TPTInitiationCohortQueries.java
> +            + "                    AND oo.concept_id = 23985 "
Please map the concepts properly. ${60}

2022-05-16 13:35 UTC, helderjosue commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TPTInitiationDataDefinitionQueries.java
> +            + "WHERE  p.voided = 0 AND e.voided = 0 AND o.voided = 0 AND o2.voided = 0 AND o3.voided = 0 "
check this implementation

this two conditions should happen on the same encounter 

``(o2.concept_id = ${23985}) AND (o2.value_coded = ${23954})) ) "
            + "           AND o3.concept_id = ${165308} AND o3.value_coded = ${1256} ``

2022-05-16 13:35 UTC, helderjosue commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TPTInitiationDataDefinitionQueries.java
> +            + "                         AND o3.concept_id = ${165308} AND o3.value_coded = ${1256} "
apply the same changes on this implementation

`AND ( ( o.concept_id = ${1719} AND o.value_coded = ${23954} ) "
            + "                                OR ( o2.concept_id = ${23985} AND o2.value_coded = ${23954} ) ) "
            + "                         AND o3.concept_id = ${165308} AND o3.value_coded = ${1256} "`

2022-05-16 13:35 UTC, helderjosue commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TPTInitiationDataDefinitionQueries.java
> +            + "                                   AND o3.concept_id = ${165308} AND o3.value_coded = ${1256} "
please check this 
`AND ( ((o.concept_id = ${1719}) AND (o.value_coded = ${23954})) "
            + "                               OR ((o2.concept_id = ${23985}) AND (o2.value_coded = ${23954})) ) "
            + "                                   AND o3.concept_id = ${165308} AND o3.value_coded = ${1256} "`

2022-05-17 09:33 UTC, helderjosue approved these changes
It looks good to me!

2022-05-25 20:36 UTC, ningosi commented
@eliazmuchave the changes you requested here, were they resolved? if yes, you might need to approve them so that I have a final look at the PR

2022-05-26 12:04 UTC, eliazmuchave commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TPTInitiationCohortQueries.java
> +            + "  OR o2.value_coded IS NULL "
Implemented

2022-05-26 12:13 UTC, ningosi approved these changes

2022-05-26 12:17 UTC, eliazmuchave approved these changes

2022-05-26 13:26 UTC, merged