Mepts |1055 Changes MQ Cat 15
jembi/openmrs-module-eptsreports pull request #764
Opened 2022-06-13 06:58 UTC by eliazmuchave

2022-06-13 16:42 UTC, psmatsinhe requested changes
@eliazmuchave we need to look the queries together

2022-06-13 16:42 UTC, psmatsinhe commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/QualityImprovement2020CohortQueries.java
> +            + "                                                      AND e2.location_id = 5 "
@eliazmuchave I think you forgot this!

2022-06-13 16:42 UTC, psmatsinhe commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/QualityImprovement2020CohortQueries.java
> +  public CohortDefinition getPatientsWithVLResultLessThan1000Between2VlRequestAfterTheseMDS(
Let's discuss in the morning @eliazmuchave

2022-06-14 13:50 UTC, psmatsinhe requested changes

2022-06-14 13:50 UTC, psmatsinhe commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/queries/QualityImprovement2020Queries.java
> +            + "         AND ( e.encounter_type = ${6} AND e.encounter_datetime BETWEEN :startDate AND :endDate) "
No parentesis

2022-06-14 13:50 UTC, psmatsinhe commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/queries/QualityImprovement2020Queries.java
> +      throw new RuntimeException("The list of encounters or concpts might not be empty ");
```suggestion
      throw new RuntimeException("The list of encounters or concepts might not be empty ");
```

2022-06-15 06:31 UTC, eliazmuchave commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/queries/QualityImprovement2020Queries.java
> +            + "         AND ( e.encounter_type = ${6} AND e.encounter_datetime BETWEEN :startDate AND :endDate) "
Fixed

2022-06-15 08:24 UTC, psmatsinhe approved these changes
Looks good to me

2022-06-15 08:24 UTC, merged