Mepts | 1061 Changes MI Cat 15
jembi/openmrs-module-eptsreports pull request #769
Opened 2022-06-15 14:03 UTC by eliazmuchave

2022-06-15 15:00 UTC, psmatsinhe requested changes
Please have a look

2022-06-15 15:00 UTC, psmatsinhe commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/IntensiveMonitoringCohortQueries.java
> +            + "       AND ee.encounter_datetime <  :endDate ";
```suggestion
            + "       AND ee.encounter_datetime <=  :endDate ";
```

2022-06-15 15:00 UTC, psmatsinhe commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/IntensiveMonitoringCohortQueries.java
> +            + " GROUP BY p.patient_id         ";
Spec

2022-06-15 15:00 UTC, psmatsinhe commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/QualityImprovement2020CohortQueries.java
> +            + "                      GROUP BY   p.patient_id ) consultation "
Falta ON

2022-06-16 06:54 UTC, ningosi commented
@eliazmuchave there is a change request in this PR that @psmatsinhe requested. He needs to review against what he requested and approve that before anyone else can act on it

2022-06-16 06:59 UTC, ningosi reviewed
See my commends on the dates you supplied

2022-06-16 06:59 UTC, ningosi commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/datasets/IntensiveMonitoringDataSet.java
> +                "startDate=${startDate},endDate=${endDate},location=${location}"));
I think this line should be

2022-06-16 06:59 UTC, ningosi commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/datasets/IntensiveMonitoringDataSet.java
> +                "startDate=${startDate},endDate=${endDate},location=${location}"));
startDate=${startDate},
endDate=${revisionEndDate},
location=${location}

2022-06-16 06:59 UTC, ningosi commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/datasets/IntensiveMonitoringDataSet.java
> +                "startDate=${startDate},endDate=${endDate},location=${location}"));
same here

2022-06-16 06:59 UTC, ningosi commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/datasets/IntensiveMonitoringDataSet.java
> +                "startDate=${startDate},endDate=${endDate},location=${location}"));
startDate=${startDate},
endDate=${revisionEndDate},
location=${location}

2022-06-16 08:37 UTC, psmatsinhe approved these changes
Looks good to me

2022-06-16 08:37 UTC, merged