Mepts 1054 mq cat 14 indicator 15 16 den num mds
jembi/openmrs-module-eptsreports pull request #778
Opened 2022-06-22 15:55 UTC by ningosi

This PR checks for the MDS per the MQ and MI CAT 15.16, only the FICHA and FILA have been tested to have patients in the database, also on checking the patients having more than 3 months on ART base don VL, was missing encounter type 51.

2022-06-27 09:07 UTC, psmatsinhe requested changes
Please format the code

2022-06-27 09:07 UTC, psmatsinhe commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/queries/QualityImprovement2020Queries.java
> +            + " ) max_vl_date GROUP BY patient_id "
@ningosi can you please format the code

2022-06-27 09:07 UTC, psmatsinhe commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/queries/ViralLoadQueries.java
> +            + ") out_p ON pp.patient_id=out_p.patient_id AND op.concept_id =%d AND op.value_coded IN(%d,%d) AND ep.encounter_type=%d AND ep.encounter_datetime=max_vl_date_and_max_ficha";
@ningosi format here also, just put it here https://www.dpriver.com/pp/sqlformat.htm

2022-07-15 08:19 UTC, ningosi commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/queries/ViralLoadQueries.java
> +        + "															 AND o.value_coded IS NOT "
Maybe we need those substitutions to point to references using the ${}

2022-07-25 12:21 UTC, ningosi commented
Hi @psmatsinhe you requested some changes on this PR, were they addressed? if Yes, accept them to give me a second chance to review

2022-08-03 07:10 UTC, psmatsinhe approved these changes
Looks good to me

2022-08-03 07:10 UTC, merged