MEPTS-1073 | TB1 - COMPLETION CASCADE
jembi/openmrs-module-eptsreports pull request #793
Opened 2022-08-31 14:44 UTC by helderjosue

2022-09-05 14:26 UTC, psmatsinhe requested changes
@helderjosue Please have a look

2022-09-05 14:26 UTC, psmatsinhe commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TPTCompletionCohortQueries.java
> +            + "    AND o2.obs_datetime < :endDate "
```suggestion
            + " AND (o2.concept_id = ${165308} AND  o2.value_coded = ${1256}   "
            + "    AND o2.obs_datetime < :endDate) "
```

2022-09-05 14:26 UTC, psmatsinhe commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TPTCompletionCohortQueries.java
> +            + " AND o2.obs_datetime < :endDate"
```suggestion
            + " AND (o2.concept_id = ${165308} AND  o2.value_coded IN (${states}) "
            + " AND o2.obs_datetime < :endDate)"
```

2022-09-05 14:26 UTC, psmatsinhe commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TPTCompletionCohortQueries.java
>              + "  AND (o2.concept_id = ${23987} AND o2.value_coded IN (${1256} , ${1705})) "
```suggestion
            + "  AND (o2.concept_id = ${23987} AND  o2.value_coded IN (${1256} , ${1705}) "
```

2022-09-05 14:26 UTC, psmatsinhe commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TPTCompletionCohortQueries.java
> +            + "  AND o2.obs_datetime < :endDate  "
```suggestion
            + "  AND o2.obs_datetime < :endDate)  "
```

2022-09-05 14:26 UTC, psmatsinhe commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TPTCompletionCohortQueries.java
> +            + "OR (o.concept_id = ${1719} AND o.value_coded IN (${23954},${165307})) "
```suggestion
            + "AND ((o2.concept_id = ${165308} AND  o2.value_coded = ${1256})   "
            + "OR (o.concept_id = ${1719} AND  o.value_coded IN (${23954},${165307}))) "
```

2022-09-05 14:26 UTC, psmatsinhe commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TPTCompletionCohortQueries.java
> +            + " AND DATEDIFF(o2.obs_datetime, regimeTPT.encounter_datetime) >= 86 AND DATEDIFF(o2.obs_datetime, regimeTPT.encounter_datetime) <= 365 AND o2.obs_datetime <= :endDate"
```suggestion
            + " AND e.location_id = :location  AND (o2.concept_id = ${165308} AND  o2.value_coded = ${1267} "
            + " AND DATEDIFF(o2.obs_datetime, regimeTPT.encounter_datetime) >= 86 AND DATEDIFF(o2.obs_datetime, regimeTPT.encounter_datetime) <= 365 AND o2.obs_datetime <= :endDate)"
```

2022-09-09 06:41 UTC, psmatsinhe requested changes
@helderjosue Please have a look at this comments

2022-09-12 09:21 UTC, helderjosue commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TPTCompletionCohortQueries.java
> +            + " AND DATEDIFF(o2.obs_datetime, regimeTPT.encounter_datetime) >= 86 AND DATEDIFF(o2.obs_datetime, regimeTPT.encounter_datetime) <= 365 AND o2.obs_datetime <= :endDate"
I pushed a commit with all suggestions applied.

2022-10-24 21:19 UTC, psmatsinhe approved these changes
Looks good to me

2022-10-24 21:20 UTC, merged