Mepts 1076 tpt initiation changes
jembi/openmrs-module-eptsreports pull request #794
Opened 2022-09-01 01:57 UTC by TinoMuianga

2022-09-05 12:14 UTC, psmatsinhe requested changes
@TinoMuianga please have a look on TB3 review comments

2022-09-05 12:14 UTC, psmatsinhe commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TPTInitiationDataDefinitionQueries.java
> +            + "                    INNER JOIN obs o3 ON e.encounter_id = o3.encounter_id "
I think this o3 is not being used!

2022-09-05 12:14 UTC, psmatsinhe commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TPTInitiationDataDefinitionQueries.java
> +            + "            AND ( o2.concept_id = ${23987} AND o2.value_coded IN ( ${1257}, ${1267} ) OR o2.value_coded IS NULL "
```suggestion
            + "            AND ( o2.concept_id = ${23987} AND (o2.value_coded IN ( ${1257}, ${1267} ) OR o2.value_coded IS NULL) "
```

2022-09-05 12:14 UTC, psmatsinhe commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TPTInitiationCohortQueries.java
>              + "       AND ( o2.concept_id = ${23987} AND o2.value_coded IN ( ${1257}, ${1267} ) OR o2.value_coded IS NULL "
```suggestion
            + "       AND ( o2.concept_id = ${23987} AND (o2.value_coded IN ( ${1257}, ${1267} ) OR o2.value_coded IS NULL) "
```

2022-09-05 12:14 UTC, psmatsinhe commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TPTInitiationCohortQueries.java
> +            + "               AND   ( o2.concept_id =  ${23987}  AND (o2.value_coded =  ${1257}  OR o2.value_coded IS NULL) "
```suggestion
            + "               AND   ( (o2.concept_id =  ${23987}  AND (o2.value_coded =  ${1257}  OR o2.value_coded IS NULL)) "
```

2022-09-05 12:14 UTC, psmatsinhe commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TPTInitiationDataDefinitionQueries.java
> +            + "            AND ( o2.concept_id = ${23987} AND o2.value_coded IN ( ${1257}, ${1267} ) OR o2.value_coded IS NULL "
```suggestion
            + "            AND ( o2.concept_id = ${23987} AND (o2.value_coded IN ( ${1257}, ${1267} ) OR o2.value_coded IS NULL) "
```

2022-09-05 13:53 UTC, TinoMuianga commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TPTInitiationDataDefinitionQueries.java
> +            + "                    INNER JOIN obs o3 ON e.encounter_id = o3.encounter_id "
Resolved

2022-09-05 13:53 UTC, TinoMuianga commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TPTInitiationDataDefinitionQueries.java
> +            + "            AND ( o2.concept_id = ${23987} AND o2.value_coded IN ( ${1257}, ${1267} ) OR o2.value_coded IS NULL "
Resolved

2022-09-05 13:53 UTC, TinoMuianga commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TPTInitiationCohortQueries.java
>              + "       AND ( o2.concept_id = ${23987} AND o2.value_coded IN ( ${1257}, ${1267} ) OR o2.value_coded IS NULL "
Resolved

2022-09-05 13:54 UTC, TinoMuianga commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TPTInitiationCohortQueries.java
> +            + "               AND   ( o2.concept_id =  ${23987}  AND (o2.value_coded =  ${1257}  OR o2.value_coded IS NULL) "
Resolved

2022-09-09 07:05 UTC, psmatsinhe requested changes
@TinoMuianga Please have a look on this

2022-09-09 07:05 UTC, psmatsinhe commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TPTInitiationDataDefinitionQueries.java
> +            + "            AND o2.obs_datetime BETWEEN :startDate AND :endDate ) "
```suggestion
            + "            AND ( o2.concept_id = ${23987} AND ( o2.value_coded IN ( ${1257}, ${1267} ) OR o2.value_coded IS NULL ) "
            + "            AND o2.obs_datetime BETWEEN :startDate AND :endDate ) ) "
```

2022-09-09 07:05 UTC, psmatsinhe commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TPTInitiationDataDefinitionQueries.java
>              + "            AND ( o2.concept_id = ${23987} AND o2.value_coded IN ( ${1257}, ${1267} ) OR o2.value_coded IS NULL ) "
```suggestion
            + "            AND ( o2.concept_id = ${23987} AND ( o2.value_coded IN ( ${1257}, ${1267} ) OR o2.value_coded IS NULL ) "
```

2022-09-09 07:05 UTC, psmatsinhe commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TPTInitiationDataDefinitionQueries.java
> +            + "            AND o2.obs_datetime BETWEEN :startDate AND :endDate ) "
```suggestion
            + "            AND o2.obs_datetime BETWEEN :startDate AND :endDate )) "
```

2022-09-09 07:05 UTC, psmatsinhe commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TPTInitiationCohortQueries.java
> +            + "       AND o2.obs_datetime BETWEEN :startDate AND :endDate ) "
```suggestion
            + "       AND ( o2.concept_id = ${23987} AND ( o2.value_coded IN ( ${1257}, ${1267} ) OR o2.value_coded IS NULL ) "
            + "       AND o2.obs_datetime BETWEEN :startDate AND :endDate )) "
```

2022-09-09 11:49 UTC, psmatsinhe approved these changes
Looks good to me

2022-09-09 11:49 UTC, merged