MEPTS-1088 | TB1: TPT Completion Cascade Css Differences
jembi/openmrs-module-eptsreports pull request #828
Opened 2022-11-22 07:59 UTC by TinoMuianga

2022-11-30 22:44 UTC, psmatsinhe requested changes
Please see this

2022-11-30 22:44 UTC, psmatsinhe commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/reports/SetupTPTCompletionReport.java
> +@Component
@TinoMuianga this should be left deprecated

2022-12-01 09:16 UTC, TinoMuianga commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/reports/SetupTPTCompletionReport.java
> +@Component
Resolved.

2022-12-12 07:35 UTC, eliazmuchave requested changes

2022-12-12 07:35 UTC, eliazmuchave commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TPTCompletionCohortQueries.java
> +
Why using composition if you have only one definition

2022-12-12 07:35 UTC, eliazmuchave commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TPTCompletionCohortQueries.java
> +            + "                  AND        o2.obs_datetime < :endDate ) ) "
Check query formatting

2022-12-12 07:35 UTC, eliazmuchave commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TPTCompletionCohortQueries.java
> +      int threeHPPiridoxinaConcept) {
Is this method called with different values?

2022-12-12 07:35 UTC, eliazmuchave commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TPTCompletionCohortQueries.java
> +      int completedConcept) {
Why define parameters instead of passing parameters in the map?

2022-12-12 07:35 UTC, eliazmuchave commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TPTCompletionCohortQueries.java
> +    SqlCohortDefinition sqlCohortDefinition = new SqlCohortDefinition();
??

2022-12-12 07:35 UTC, eliazmuchave commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TPTCompletionCohortQueries.java
> +    SqlCohortDefinition sqlCohortDefinition = new SqlCohortDefinition();
??

2022-12-12 07:35 UTC, eliazmuchave commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TPTCompletionCohortQueries.java
> +      int threeHPConcept) {
?

2022-12-12 07:35 UTC, eliazmuchave commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TPTCompletionCohortQueries.java
> +      int masterCardEncounterType) {
?

2022-12-12 07:35 UTC, eliazmuchave commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TPTCompletionCohortQueries.java
> +      int masterCardEncounterType) {
??

2022-12-12 07:35 UTC, eliazmuchave commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TPTCompletionCohortQueries.java
> -      int threeHPPiridoxinaConcept) {
?

2022-12-16 11:45 UTC, TinoMuianga commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TPTCompletionCohortQueries.java
> +
Changed from Composition to Cohort Definition

2022-12-16 12:53 UTC, TinoMuianga commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TPTCompletionCohortQueries.java
> +            + "                  AND        o2.obs_datetime < :endDate ) ) "
Fixed query formation

2023-01-25 07:50 UTC, psmatsinhe approved these changes
Looks good to me

2023-01-25 07:51 UTC, merged