MEPTS - 1150 | Requirements Fix - Resumo Mensal
jembi/openmrs-module-eptsreports pull request #868
Opened 2023-01-26 13:44 UTC by TinoMuianga

2023-01-30 07:10 UTC, helderjosue approved these changes
Looks good to me!

2023-02-01 09:41 UTC, eliazmuchave requested changes

2023-02-01 09:41 UTC, eliazmuchave commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/queries/ResumoMensalQueries.java
> +    query.append(
Not implemented according to specification

2023-02-10 07:14 UTC, eliazmuchave approved these changes
Looks good to me

2023-02-10 07:14 UTC, merged