MEPTS 1160 | TX_TB Changes For March 2023
jembi/openmrs-module-eptsreports pull request #871
Opened 2023-02-09 10:34 UTC by TinoMuianga

2023-02-14 09:59 UTC, eliazmuchave requested changes

2023-02-14 09:59 UTC, eliazmuchave commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/reports/SetupTxTbMonthlyCascadeReport.java
> -    return "TX TB Monthly Cascade Report to PEPFAR";
Update the TxTb Setup

2023-02-14 09:59 UTC, eliazmuchave commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TXTBCohortQueries.java
> +    return cd;
No need to create composition without preposition.

2023-02-14 09:59 UTC, eliazmuchave commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TXTBCohortQueries.java
> +            + "             GROUP BY transferred_out.patient_id";
This query is not in accordance with the specification

2023-02-14 11:31 UTC, TinoMuianga commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/reports/SetupTxTbMonthlyCascadeReport.java
> -    return "TX TB Monthly Cascade Report to PEPFAR";
Solved

2023-02-15 12:04 UTC, eliazmuchave approved these changes

2023-02-15 12:05 UTC, merged