MEPTS 1218 | MQ Cat 13 Diff ICAP DB
jembi/openmrs-module-eptsreports pull request #920
Opened 2023-04-03 09:24 UTC by TinoMuianga

2023-04-18 08:38 UTC, psmatsinhe requested changes
@TinoMuianga please put the specs of the pregnancy method

2023-04-18 08:38 UTC, psmatsinhe commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/queries/QualityImprovement2020Queries.java
> +  }
Please put the spec of this method

2023-04-18 08:49 UTC, psmatsinhe requested changes
Looks good to me, Please put the specs

2023-04-19 12:43 UTC, TinoMuianga commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/queries/QualityImprovement2020Queries.java
> +  }
Done

2023-04-24 12:04 UTC, psmatsinhe approved these changes
Looks good to me

2023-04-24 12:05 UTC, merged