Impelementing The first clinical consultation query on Breatsfeeding …
jembi/openmrs-module-eptsreports pull request #940
Opened 2023-04-28 09:46 UTC by Emmanuel0077

…and pregnant queries

2023-04-28 14:07 UTC, helderjosue commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/QualityImprovement2020CohortQueries.java
> +          "A AND breastfeedingOnPeriod AND D AND resultCd4 AND NOT (C OR E OR pregnantOnPeriod) AND AGE");
This changes should not be applied on the numerator, please revert the changes and apply accordingly

2023-04-28 14:08 UTC, helderjosue commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/QualityImprovement2020CohortQueries.java
> +                    + "       AND o.concept_id = ${question} "
Please write the conditions in a more readable way

2023-04-28 14:09 UTC, helderjosue requested changes
Please check the comments

2023-05-02 09:03 UTC, helderjosue approved these changes
Looks good to me. Ready for final review

2023-05-09 10:28 UTC, eliazmuchave requested changes

2023-05-09 10:28 UTC, eliazmuchave commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/QualityImprovement2020CohortQueries.java
> +        "A OR (D AND breastfeedingOnPeriod) AND NOT (C OR E OR pregnantOnPeriod) AND AGE");
Does not meet the requirements

2023-05-09 12:55 UTC, eliazmuchave approved these changes
Looks good to me

2023-05-09 13:56 UTC, eliazmuchave approved these changes
Looks good to me

2023-05-09 13:56 UTC, eliazmuchave commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/QualityImprovement2020CohortQueries.java
> +   *     “Lactante=Sim” na mesma consulta inicial, será considerada como grávida. <<<<<<< HEAD
Resolve this conflicts

2023-05-09 13:57 UTC, merged