MEPTS 1242 | MQ CAT 13 Changes June 2023
jembi/openmrs-module-eptsreports pull request #945
Opened 2023-05-02 13:30 UTC by TinoMuianga

2023-05-11 09:44 UTC, eliazmuchave requested changes

2023-05-11 09:44 UTC, eliazmuchave commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/QualityImprovement2020CohortQueries.java
> +          "((A AND NOT C) OR B1) AND NOT (F OR E OR DD OR ABANDONED1LINE) AND age");
Not meet requirements

2023-05-11 09:44 UTC, eliazmuchave commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/QualityImprovement2020CohortQueries.java
> +        "( B2NEW OR RESTARTED OR (B3 AND NOT B3E) ) AND NOT (ABANDONED1LINE OR B5E)");
Doesn't meet requirements

2023-05-11 09:44 UTC, eliazmuchave commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/QualityImprovement2020CohortQueries.java
> +            "((B1Den18 AND B4CV50 AND PrimeiraLinha AND H50) AND NOT (E or F)");
Doesn't meet the requirements - B4CV50 and B1Den18

2023-05-11 09:44 UTC, eliazmuchave commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/QualityImprovement2020CohortQueries.java
> -            + QualityImprovement2020Queries.getPregnancyDuringPeriod()
Doesn't meet the requirements

2023-05-11 10:02 UTC, TinoMuianga commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/QualityImprovement2020CohortQueries.java
> +          "((A AND NOT C) OR B1) AND NOT (F OR E OR DD OR ABANDONED1LINE) AND age");
Solved

2023-05-11 14:39 UTC, TinoMuianga commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/QualityImprovement2020CohortQueries.java
> -            + QualityImprovement2020Queries.getPregnancyDuringPeriod()
No longer using this implementation

2023-05-11 14:39 UTC, TinoMuianga commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/QualityImprovement2020CohortQueries.java
> +            "((B1Den18 AND B4CV50 AND PrimeiraLinha AND H50) AND NOT (E or F)");
Solved

2023-05-12 08:02 UTC, eliazmuchave requested changes

2023-05-12 08:02 UTC, eliazmuchave commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/queries/QualityImprovement2020Queries.java
> +            + "                   AND ( e.encounter_type = ${53} AND e.encounter_datetime BETWEEN :startDate AND :endDate ) "
Not obs_datetime?

2023-05-12 08:02 UTC, eliazmuchave commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/queries/QualityImprovement2020Queries.java
> +            + "                   SELECT p.patient_id, MIN(e.encounter_datetime) as first_carga_viral "
Should select the oldest date

2023-05-12 08:02 UTC, eliazmuchave commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/queries/QualityImprovement2020Queries.java
> +            + "                  ) AS mulher ON mulher.patient_id = p.patient_id "
Should check the pregnancy concept in Ficha Resumo as well

2023-05-12 08:02 UTC, eliazmuchave commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/queries/QualityImprovement2020Queries.java
> +            + "                                          ) most_recent  ON p.patient_id = most_recent.patient_id   "
Should select the record of the oldest concept, not the Ficha Resumo

2023-05-12 09:09 UTC, TinoMuianga commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/queries/QualityImprovement2020Queries.java
> +            + "                   SELECT p.patient_id, MIN(e.encounter_datetime) as first_carga_viral "
Done

2023-05-12 09:12 UTC, TinoMuianga commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/queries/QualityImprovement2020Queries.java
> +            + "                   SELECT p.patient_id, MIN(e.encounter_datetime) as first_carga_viral "
Done

2023-05-12 11:35 UTC, TinoMuianga commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/queries/QualityImprovement2020Queries.java
> +            + "                  ) AS mulher ON mulher.patient_id = p.patient_id "
Done

2023-05-15 10:24 UTC, eliazmuchave approved these changes
Looks good to me

2023-05-15 10:30 UTC, merged