MEPTS 1234 | Unit Tests For TX_PVLS Breastfeeding Cohort
jembi/openmrs-module-eptsreports pull request #946
Opened 2023-05-03 08:00 UTC by Emmanuel0077

2023-05-03 15:14 UTC, psmatsinhe approved these changes
Looks good to me

2023-05-10 09:00 UTC, eliazmuchave requested changes

2023-05-10 09:00 UTC, eliazmuchave commented on api/src/test/java/org/openmrs/module/eptsreports/reporting/intergrated/library/cohorts/TxPvlsCohortQueriesTest.java
> +    parameters.put(new Parameter("startDate", "Start Date", Date.class), getStartDate());
This is never used

2023-05-10 09:00 UTC, eliazmuchave commented on api/src/test/java/org/openmrs/module/eptsreports/reporting/intergrated/library/cohorts/TxPvlsCohortQueriesTest.java
> +    parameters.put(new Parameter("startDate", "Start Date", Date.class), getStartDate());
This is never used

2023-05-10 09:09 UTC, Emmanuel0077 commented on api/src/test/java/org/openmrs/module/eptsreports/reporting/intergrated/library/cohorts/TxPvlsCohortQueriesTest.java
> +    parameters.put(new Parameter("startDate", "Start Date", Date.class), getStartDate());
I will remove it, as soon as possible

2023-05-15 07:30 UTC, merged