MEPTS-1255 | MI CAT 15 Changes For June Release
jembi/openmrs-module-eptsreports pull request #971
Opened 2023-05-25 12:01 UTC by Emmanuel0077

2023-05-26 08:53 UTC, iteliolucas commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/IntensiveMonitoringCohortQueries.java
> +                    + "       AND ( o.concept_id = 2015 "
2015 is not mapped, please add the corresponding mapping

2023-05-26 08:54 UTC, iteliolucas commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/IntensiveMonitoringCohortQueries.java
> +                    + "             AND o.value_coded IN ( 23748, 6293, 23749, 29, "
23748, 6293, 23749, 29 and so on are not mapped, please add the corresponding mapping

2023-05-26 08:57 UTC, Emmanuel0077 commented
Please, consider the last commit, these changes were removed because these
queries already exited in the code

Itélio Lucas ***@***.***> escreveu em sex., 26/05/2023 às
10:54 :

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In
> api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/IntensiveMonitoringCohortQueries.java
> <https://github.com/jembi/openmrs-module-eptsreports/pull/971#discussion_r1206452789>
> :
>
> > +    map.put("6", hivMetadata.getAdultoSeguimentoEncounterType().getEncounterTypeId());
> +    map.put("6", hivMetadata.getAdultoSeguimentoEncounterType().getEncounterTypeId());
> +    map.put("6", hivMetadata.getAdultoSeguimentoEncounterType().getEncounterTypeId());
> +    map.put("6", hivMetadata.getAdultoSeguimentoEncounterType().getEncounterTypeId());
> +
> +
> +    String query =
> +            " SELECT p.patient_id "
> +                    + "FROM   patient p "
> +                    + "       inner join encounter e "
> +                    + "               ON e.patient_id = p.patient_id "
> +                    + "       inner join obs o "
> +                    + "               ON o.encounter_id = e.encounter_id "
> +                    + "WHERE  e.encounter_type = ${6} "
> +                    + "       AND ( o.concept_id = 2015 "
> +                    + "             AND o.value_coded IN ( 23748, 6293, 23749, 29, "
>
> 23748, 6293, 23749, 29 and so on are not mapped, please add the
> corresponding mapping
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/jembi/openmrs-module-eptsreports/pull/971#pullrequestreview-1445668495>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWRGQ7O5J2OVNC4ZNP4TUQTXIBVT3ANCNFSM6AAAAAAYOXQEUU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-05-26 09:00 UTC, Emmanuel0077 commented
The correct mapping was made in the second commit


Emmanuel Vicente ***@***.***> escreveu em sex., 26/05/2023
às 10:57 :

> Please, consider the last commit, these changes were removed because these
> queries already exited in the code
>
> Itélio Lucas ***@***.***> escreveu em sex., 26/05/2023 às
> 10:54 :
>
>> ***@***.**** commented on this pull request.
>> ------------------------------
>>
>> In
>> api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/IntensiveMonitoringCohortQueries.java
>> <https://github.com/jembi/openmrs-module-eptsreports/pull/971#discussion_r1206452789>
>> :
>>
>> > +    map.put("6", hivMetadata.getAdultoSeguimentoEncounterType().getEncounterTypeId());
>> +    map.put("6", hivMetadata.getAdultoSeguimentoEncounterType().getEncounterTypeId());
>> +    map.put("6", hivMetadata.getAdultoSeguimentoEncounterType().getEncounterTypeId());
>> +    map.put("6", hivMetadata.getAdultoSeguimentoEncounterType().getEncounterTypeId());
>> +
>> +
>> +    String query =
>> +            " SELECT p.patient_id "
>> +                    + "FROM   patient p "
>> +                    + "       inner join encounter e "
>> +                    + "               ON e.patient_id = p.patient_id "
>> +                    + "       inner join obs o "
>> +                    + "               ON o.encounter_id = e.encounter_id "
>> +                    + "WHERE  e.encounter_type = ${6} "
>> +                    + "       AND ( o.concept_id = 2015 "
>> +                    + "             AND o.value_coded IN ( 23748, 6293, 23749, 29, "
>>
>> 23748, 6293, 23749, 29 and so on are not mapped, please add the
>> corresponding mapping
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/jembi/openmrs-module-eptsreports/pull/971#pullrequestreview-1445668495>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AWRGQ7O5J2OVNC4ZNP4TUQTXIBVT3ANCNFSM6AAAAAAYOXQEUU>
>> .
>> You are receiving this because you authored the thread.Message ID:
>> ***@***.***>
>>
>

2023-05-26 12:56 UTC, iteliolucas commented
Looks ok

2023-05-29 07:05 UTC, eliazmuchave requested changes

2023-05-29 07:05 UTC, eliazmuchave commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/QualityImprovement2020CohortQueries.java
>          EptsReportUtils.map(
This definition is no longer used, remove it from cohort search

2023-05-29 07:47 UTC, eliazmuchave approved these changes
Looks good to me

2023-05-29 07:53 UTC, merged